### PR TITLE
Deploy initial version of seamlesswallet.transactions-query service to live

### PR DESCRIPTION
**Pull request by makobernal**
Related Epic: https://github.com/Casumo/Home/issues/20379
Related Issue(s): https://github.com/casumo/home/issues/20374 / https://github.com/casumo/home/issues/20376

The new has been running on casumotest for a while, and the functionality is quite simple. Thanks to all the groundwork by @rieske and his `payments-query` service, this has been really easy to set up.

This PR goes beyond the changes, and I'm actually asking to review the whole thing.

- Swagger: http://seamlesswallet-transactions-query.at.casumotest.local:8080/swagger-ui.html
- Metrics: http://grafana.casumotest.local/dashboard/db/seamlesswallet-transactions-query?refresh=1m&orgId=1
- Logs: http://kibana.casumotest.local/app/kibana#/discover/39a92e60-65a8-11e8-be49-41ec53b456b2?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-jetty*',key:source,negate:!f,params:(query:%2Fvar%2Flog%2Fseamlesswallet-transactions-query%2Fjson.log,type:phrase),type:phrase,value:%2Fvar%2Flog%2Fseamlesswallet-transactions-query%2Fjson.log),query:(match:(source:(query:%2Fvar%2Flog%2Fseamlesswallet-transactions-query%2Fjson.log,type:phrase))))),index:'filebeat-jetty*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))

The service will be deployed to `live` after a merge to master.

### CODE REVIEW

**Comment by rieske** [comment]
Tracing looks to be working too: http://zipkin-server.casumotest.cloud/zipkin/?serviceName=seamlesswallet-transactions-query

**Comment by rieske** [comment]
https://github.com/Casumo/seamlesswallet.transactions-query/blob/master/src/main/java/com/casumo/seamlesswallet/transactions/infrastructure/tracing/TracingStatementInterceptor.java

This one was a workaround for https://github.com/openzipkin/brave/issues/561
A potential fix was released here: https://github.com/openzipkin/brave/pull/700 and made it into brave 5.0
Nothing critical, but might be worth evaluating.

**Comment by rieske** [comment]
Looks familiar :)
The issues I found with this code (and mine) - unneeded test cometd dependency and typo in `localhost` in `application.yml`

**Comment by makobernal** [comment]
I'll take the above points see if they can be fixed on a branch.

**Pull request merged**
